package task

class AggregateException(override val cause: Throwable): Exception()